# 1. Import All Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import psycopg2
from sqlalchemy import create_engine

warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

# 2. Load the Dataset

In [2]:
df = pd.read_csv('D:\\Hospital_Performance_Dashboard\\Hospital_Raw_Data.csv')
df.head()

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Admission_Date,Discharge_Date,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome
0,PAT000001,23.0,Male,Gynecology,Cancer,Low,06:47.7,06:47.7,2,79,DOC0350,Employer,485,0.0,Recovered
1,PAT000002,48.0,Male,Neurology,Kidney Disease,Medium,52:16.6,52:16.6,6,167,DOC0267,Private,3487,0.0,Improved
2,PAT000003,NaN,Male,Neurology,Stroke,Low,51:37.1,51:37.1,3,281,DOC0197,Self-Pay,716,0.0,Recovered
3,PAT000004,85.0,Male,Emergency,Asthma,Medium,17:09.6,17:09.6,2,271,DOC0009,Government,2111,0.0,Recovered
4,PAT000005,93.0,Female,Neurology,Pneumonia,Medium,48:22.2,48:22.2,7,112,DOC0219,Self-Pay,4968,0.0,Transferred

In [3]:
# All Information of Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           20000 non-null  object
 1   Age                  18425 non-null  float64
 2   Gender               20000 non-null  object
 3   Department           20000 non-null  object
 4   Diagnosis            20000 non-null  object
 5   Severity_Level       20000 non-null  object
 6   Admission_Date       20000 non-null  object
 7   Discharge_Date       20000 non-null  object
 8   Length_of_Stay_Days  20000 non-null  int64
 9   Wait_Time_Minutes    20000 non-null  int64
 10  Doctor_ID            20000 non-null  object
 11  Insurance_Type       20000 non-null  object
 12  Treatment_Cost_USD   20000 non-null  int64
 13  Readmission_Flag     19682 non-null  float64
 14  Outcome              20000 non-null  object
dtypes: float64(2), int64(3), object(10)
memory usage: 2.3+ MB

# 3. Data Cleaning

### 3.1 Missing Values

In [4]:
missing_summary = df.isnull().sum()
missing_pct = (missing_summary / len(df) * 100).round(2)

missing_data = pd.DataFrame({ "Missing Count": missing_summary, "Missing %": missing_pct})
missing_report = missing_data[missing_data["Missing Count"] > 0].sort_values("Missing Count", ascending=False)

print("Columns with Missing Values:")
missing_report

Columns with Missing Values:

                  Missing Count  Missing %
Age                        1575       7.88
Readmission_Flag            318       1.59

### 3.2 Duplicate Records

In [5]:
All_duplicates = df.duplicated().sum()
patient_id_duplicate = df.duplicated(subset=["Patient_ID"]).sum()

print(f"Fully duplicated rows: {All_duplicates}")
print(f"Duplicate Patient id :   {patient_id_duplicate}")

dup_order_ids = df[df.duplicated(subset=["Patient_ID"], keep=False)].sort_values("Patient_ID")
dup_order_ids[["Patient_ID", "Doctor_ID","Department","Diagnosis"]]

Fully duplicated rows: 0
Duplicate Patient id :   1345

      Patient_ID Doctor_ID       Department      Diagnosis
5      PAT000006   DOC0499        Emergency       Diabetes
24     PAT000006   DOC0355       Pediatrics       Fracture
15     PAT000016   DOC0471         Oncology      Infection
32     PAT000016   DOC0367  General Surgery       Fracture
38     PAT000016   DOC0481        Neurology      Pneumonia
...          ...       ...              ...            ...
17357  PAT017357   DOC0229      Dermatology         Stroke
17356  PAT017357   DOC0448      Orthopedics  Heart Disease
17420  PAT017357   DOC0140       Pediatrics      Pneumonia
17387  PAT017357   DOC0423      Dermatology      Pneumonia
19999  PAT017357   DOC0495        Emergency         Asthma

[1410 rows x 4 columns]

### 3.3 Remove Duplicate Records

In [6]:
before = len(df)
df = df.drop_duplicates(subset=["Patient_ID"], keep="first")
after = len(df)

print(f"Removed {before - after} duplicate Patient_ID rows")
print(f"New shape: {df.shape}")

assert df["Patient_ID"].is_unique, "Patient_ID still has Duplicate Records!"
print("Patient_ID is now unique")

Removed 1345 duplicate Patient_ID rows
New shape: (18655, 15)
Patient_ID is now unique

### 3.4 Handle Missing Values

#### Age Column Consist of Missing values fill with Median age

In [7]:
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)
print(f"Filled missing Age values with median = {median_age}")

Filled missing Age values with median = 48.0

In [8]:
categorical_cols = ['Gender', 'Department', 'Diagnosis', 'Severity_Level', 'Insurance_Type', 'Outcome']
numeric_cols = ['Age', 'Length_of_Stay_Days', 'Wait_Time_Minutes', 'Treatment_Cost_USD']

for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

df['Readmission_Flag'] = df['Readmission_Flag'].fillna(0)

print("Missing values after imputation:")
print(df.isna().sum())

Missing values after imputation:
Patient_ID             0
Age                    0
Gender                 0
Department             0
Diagnosis              0
Severity_Level         0
Admission_Date         0
Discharge_Date         0
Length_of_Stay_Days    0
Wait_Time_Minutes      0
Doctor_ID              0
Insurance_Type         0
Treatment_Cost_USD     0
Readmission_Flag       0
Outcome                0
dtype: int64

### 3.5 Fixing Date Columns

In [9]:
print("Are Admission_Date and Discharge_Date identical in every row?",
      (df['Admission_Date'] == df['Discharge_Date']).all())
print(df[['Admission_Date', 'Discharge_Date']].head())

df = df.drop(columns=['Admission_Date', 'Discharge_Date'])

Are Admission_Date and Discharge_Date identical in every row? True
  Admission_Date Discharge_Date
0        06:47.7        06:47.7
1        52:16.6        52:16.6
2        51:37.1        51:37.1
3        17:09.6        17:09.6
4        48:22.2        48:22.2

### 3.6 Fix Data Types

In [10]:
df['Age'] = df['Age'].astype(int)
df['Length_of_Stay_Days'] = df['Length_of_Stay_Days'].astype(int)
df['Wait_Time_Minutes'] = df['Wait_Time_Minutes'].astype(int)
df['Treatment_Cost_USD'] = df['Treatment_Cost_USD'].astype(float).round(2)

for col in categorical_cols:
    df[col] = df[col].astype('category')

df.dtypes

Patient_ID               object
Age                       int32
Gender                 category
Department             category
Diagnosis              category
Severity_Level         category
Length_of_Stay_Days       int32
Wait_Time_Minutes         int32
Doctor_ID                object
Insurance_Type         category
Treatment_Cost_USD      float64
Readmission_Flag        float64
Outcome                category
dtype: object

In [11]:
print(f"Final cleaned shape: {df.shape}")
df.head()

Final cleaned shape: (18655, 13)

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome
0,PAT000001,23,Male,Gynecology,Cancer,Low,2,79,DOC0350,Employer,485.0,0.0,Recovered
1,PAT000002,48,Male,Neurology,Kidney Disease,Medium,6,167,DOC0267,Private,3487.0,0.0,Improved
2,PAT000003,48,Male,Neurology,Stroke,Low,3,281,DOC0197,Self-Pay,716.0,0.0,Recovered
3,PAT000004,85,Male,Emergency,Asthma,Medium,2,271,DOC0009,Government,2111.0,0.0,Recovered
4,PAT000005,93,Female,Neurology,Pneumonia,Medium,7,112,DOC0219,Self-Pay,4968.0,0.0,Transferred

# 4. Data Transformation

### 4.1 Cost Per Day

In [12]:
 df['Cost_Per_Day_USD'] = (df['Treatment_Cost_USD'] / df['Length_of_Stay_Days']).round(2)
df[['Treatment_Cost_USD', 'Length_of_Stay_Days', 'Cost_Per_Day_USD']].head()

   Treatment_Cost_USD  Length_of_Stay_Days  Cost_Per_Day_USD
0               485.0                    2            242.50
1              3487.0                    6            581.17
2               716.0                    3            238.67
3              2111.0                    2           1055.50
4              4968.0                    7            709.71

### 4.2 Age Groups

In [13]:
age_bins = [0, 12, 18, 35, 50, 65, 120]
age_labels = ['Child (0-12)', 'Teen (13-18)', 'Young Adult (19-35)', 'Adult (36-50)', 'Senior (51-65)', 'Elderly (65+)']
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels, right=True, include_lowest=True)

df[['Age', 'Age_Group']].head()

   Age            Age_Group
0   23  Young Adult (19-35)
1   48        Adult (36-50)
2   48        Adult (36-50)
3   85        Elderly (65+)
4   93        Elderly (65+)

### 4.3 Wait Time Buckets

In [14]:
wait_bins = [0, 30, 60, 120, 180, 300]
wait_labels = ['<30 min', '30-60 min', '1-2 hr', '2-3 hr', '3-5 hr']
df['Wait_Time_Bucket'] = pd.cut(df['Wait_Time_Minutes'], bins=wait_bins, labels=wait_labels, include_lowest=True)

df[['Wait_Time_Minutes', 'Wait_Time_Bucket']].head()

   Wait_Time_Minutes Wait_Time_Bucket
0                 79           1-2 hr
1                167           2-3 hr
2                281           3-5 hr
3                271           3-5 hr
4                112           1-2 hr

### 4.4 Length of Stay Days

In [15]:
los_bins = [0, 1, 3, 7, 14, 100]
los_labels = ['Same day', 'Short (2-3d)', 'Medium (4-7d)', 'Long (8-14d)', 'Extended (15d+)']
df['Stay_Category'] = pd.cut(df['Length_of_Stay_Days'], bins=los_bins, labels=los_labels, include_lowest=True)
df[['Length_of_Stay_Days', 'Stay_Category']].head()

   Length_of_Stay_Days  Stay_Category
0                    2   Short (2-3d)
1                    6  Medium (4-7d)
2                    3   Short (2-3d)
3                    2   Short (2-3d)
4                    7  Medium (4-7d)

### 4.5 Ordinal Severity Score

In [16]:
severity_order = {'Low': 1, 'Medium': 2, 'High': 3, 'Critical': 4, 'Unknown': np.nan}
df['Severity_Score'] = df['Severity_Level'].map(severity_order)

df[['Severity_Level', 'Severity_Score']].drop_duplicates().sort_values('Severity_Score')

   Severity_Level Severity_Score
17       Critical            4.0
8            High            3.0
0             Low            1.0
1          Medium            2.0

### 4.6 Readable Readmission Label

In [17]:
df['Readmitted'] = df['Readmission_Flag'].map({0: 'No', 1: 'Yes'})
df[['Readmission_Flag', 'Readmitted']].head()

   Readmission_Flag Readmitted
0               0.0         No
1               0.0         No
2               0.0         No
3               0.0         No
4               0.0         No

In [18]:
print(f"Shape after feature engineering: {df.shape}")
df.head()

Shape after feature engineering: (18655, 19)

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome,Cost_Per_Day_USD,Age_Group,Wait_Time_Bucket,Stay_Category,Severity_Score,Readmitted
0,PAT000001,23,Male,Gynecology,Cancer,Low,2,79,DOC0350,Employer,485.0,0.0,Recovered,242.50,Young Adult (19-35),1-2 hr,Short (2-3d),1.0,No
1,PAT000002,48,Male,Neurology,Kidney Disease,Medium,6,167,DOC0267,Private,3487.0,0.0,Improved,581.17,Adult (36-50),2-3 hr,Medium (4-7d),2.0,No
2,PAT000003,48,Male,Neurology,Stroke,Low,3,281,DOC0197,Self-Pay,716.0,0.0,Recovered,238.67,Adult (36-50),3-5 hr,Short (2-3d),1.0,No
3,PAT000004,85,Male,Emergency,Asthma,Medium,2,271,DOC0009,Government,2111.0,0.0,Recovered,1055.50,Elderly (65+),3-5 hr,Short (2-3d),2.0,No
4,PAT000005,93,Female,Neurology,Pneumonia,Medium,7,112,DOC0219,Self-Pay,4968.0,0.0,Transferred,709.71,Elderly (65+),1-2 hr,Medium (4-7d),2.0,No

# 5. Save the File

In [19]:
df.to_csv("D:\\Hospital_Performance_Dashboard\\Hospital_clean_data.csv", index=False)
print("Clean dataset saved successfully.")
print('Final shape:', df.shape)
df.head()

Clean dataset saved successfully.
Final shape: (18655, 19)

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome,Cost_Per_Day_USD,Age_Group,Wait_Time_Bucket,Stay_Category,Severity_Score,Readmitted
0,PAT000001,23,Male,Gynecology,Cancer,Low,2,79,DOC0350,Employer,485.0,0.0,Recovered,242.50,Young Adult (19-35),1-2 hr,Short (2-3d),1.0,No
1,PAT000002,48,Male,Neurology,Kidney Disease,Medium,6,167,DOC0267,Private,3487.0,0.0,Improved,581.17,Adult (36-50),2-3 hr,Medium (4-7d),2.0,No
2,PAT000003,48,Male,Neurology,Stroke,Low,3,281,DOC0197,Self-Pay,716.0,0.0,Recovered,238.67,Adult (36-50),3-5 hr,Short (2-3d),1.0,No
3,PAT000004,85,Male,Emergency,Asthma,Medium,2,271,DOC0009,Government,2111.0,0.0,Recovered,1055.50,Elderly (65+),3-5 hr,Short (2-3d),2.0,No
4,PAT000005,93,Female,Neurology,Pneumonia,Medium,7,112,DOC0219,Self-Pay,4968.0,0.0,Transferred,709.71,Elderly (65+),1-2 hr,Medium (4-7d),2.0,No

# 6. Data Modeling

### 6.1 Patient Records from Dataset

In [20]:
patients = (
    df[['Patient_ID', 'Age', 'Gender', 'Age_Group']]
    .drop_duplicates(subset='Patient_ID')
    .reset_index(drop=True)
)

print(f"patients shape: {patients.shape}")
print(f"Duplicate Patient_IDs: {patients['Patient_ID'].duplicated().sum()}")
patients.head()

patients shape: (18655, 4)
Duplicate Patient_IDs: 0

  Patient_ID  Age  Gender            Age_Group
0  PAT000001   23    Male  Young Adult (19-35)
1  PAT000002   48    Male        Adult (36-50)
2  PAT000003   48    Male        Adult (36-50)
3  PAT000004   85    Male        Elderly (65+)
4  PAT000005   93  Female        Elderly (65+)

### 6.2 Doctors Records from Dataset

In [21]:
doctors = (
    df.groupby('Doctor_ID', as_index=False)
      .agg(
          Total_Patients_Treated=('Patient_ID', 'count'),
          Departments_Covered=('Department', 'nunique'),
          Avg_Treatment_Cost_USD=('Treatment_Cost_USD', 'mean'),
          Avg_Length_of_Stay_Days=('Length_of_Stay_Days', 'mean'),
          Readmission_Rate_Pct=('Readmission_Flag', lambda x: round(x.mean() * 100, 1)),
      )
)
doctors['Avg_Treatment_Cost_USD'] = doctors['Avg_Treatment_Cost_USD'].round(2)
doctors['Avg_Length_of_Stay_Days'] = doctors['Avg_Length_of_Stay_Days'].round(1)

print(f"doctors shape: {doctors.shape}")
print(f"Duplicate Doctor_IDs: {doctors['Doctor_ID'].duplicated().sum()}")
doctors.head()

doctors shape: (500, 6)
Duplicate Doctor_IDs: 0

,Doctor_ID,Total_Patients_Treated,Departments_Covered,Avg_Treatment_Cost_USD,Avg_Length_of_Stay_Days,Readmission_Rate_Pct
0,DOC0001,37,9,3879.76,4.6,8.1
1,DOC0002,40,9,4950.32,6.0,5.0
2,DOC0003,44,10,6355.52,6.3,4.5
3,DOC0004,45,10,5051.96,6.2,8.9
4,DOC0005,33,9,4896.82,6.0,12.1

### 6.3 Visits Record from Dataset

In [22]:
visit_cols = [
    'Patient_ID', 'Doctor_ID', 'Department', 'Diagnosis', 'Severity_Level', 'Severity_Score',
    'Length_of_Stay_Days', 'Stay_Category', 'Wait_Time_Minutes', 'Wait_Time_Bucket',
    'Insurance_Type', 'Treatment_Cost_USD', 'Cost_Per_Day_USD',
    'Readmission_Flag', 'Readmitted', 'Outcome'
]

visits = df[visit_cols].copy()
visits.insert(0, 'Visit_ID', ['V' + str(i + 1).zfill(6) for i in range(len(visits))])

print(f"visits shape: {visits.shape}")
visits.head()

visits shape: (18655, 17)

,Visit_ID,Patient_ID,Doctor_ID,Department,Diagnosis,Severity_Level,Severity_Score,Length_of_Stay_Days,Stay_Category,Wait_Time_Minutes,Wait_Time_Bucket,Insurance_Type,Treatment_Cost_USD,Cost_Per_Day_USD,Readmission_Flag,Readmitted,Outcome
0,V000001,PAT000001,DOC0350,Gynecology,Cancer,Low,1.0,2,Short (2-3d),79,1-2 hr,Employer,485.0,242.50,0.0,No,Recovered
1,V000002,PAT000002,DOC0267,Neurology,Kidney Disease,Medium,2.0,6,Medium (4-7d),167,2-3 hr,Private,3487.0,581.17,0.0,No,Improved
2,V000003,PAT000003,DOC0197,Neurology,Stroke,Low,1.0,3,Short (2-3d),281,3-5 hr,Self-Pay,716.0,238.67,0.0,No,Recovered
3,V000004,PAT000004,DOC0009,Emergency,Asthma,Medium,2.0,2,Short (2-3d),271,3-5 hr,Government,2111.0,1055.50,0.0,No,Recovered
4,V000005,PAT000005,DOC0219,Neurology,Pneumonia,Medium,2.0,7,Medium (4-7d),112,1-2 hr,Self-Pay,4968.0,709.71,0.0,No,Transferred

### 6.4 Rejoin & compare to Original

In [23]:
rejoined = (
    visits
    .merge(patients, on='Patient_ID', how='left')
    .merge(doctors[['Doctor_ID']], on='Doctor_ID', how='left')  # just confirming the FK resolves
)

print(f"Original rows: {len(df)} | Rejoined rows: {len(rejoined)}")
print(f"Row counts match: {len(df) == len(rejoined)}")
rejoined.head()

Original rows: 18655 | Rejoined rows: 18655
Row counts match: True

,Visit_ID,Patient_ID,Doctor_ID,Department,Diagnosis,Severity_Level,Severity_Score,Length_of_Stay_Days,Stay_Category,Wait_Time_Minutes,Wait_Time_Bucket,Insurance_Type,Treatment_Cost_USD,Cost_Per_Day_USD,Readmission_Flag,Readmitted,Outcome,Age,Gender,Age_Group
0,V000001,PAT000001,DOC0350,Gynecology,Cancer,Low,1.0,2,Short (2-3d),79,1-2 hr,Employer,485.0,242.50,0.0,No,Recovered,23,Male,Young Adult (19-35)
1,V000002,PAT000002,DOC0267,Neurology,Kidney Disease,Medium,2.0,6,Medium (4-7d),167,2-3 hr,Private,3487.0,581.17,0.0,No,Improved,48,Male,Adult (36-50)
2,V000003,PAT000003,DOC0197,Neurology,Stroke,Low,1.0,3,Short (2-3d),281,3-5 hr,Self-Pay,716.0,238.67,0.0,No,Recovered,48,Male,Adult (36-50)
3,V000004,PAT000004,DOC0009,Emergency,Asthma,Medium,2.0,2,Short (2-3d),271,3-5 hr,Government,2111.0,1055.50,0.0,No,Recovered,85,Male,Elderly (65+)
4,V000005,PAT000005,DOC0219,Neurology,Pneumonia,Medium,2.0,7,Medium (4-7d),112,1-2 hr,Self-Pay,4968.0,709.71,0.0,No,Transferred,93,Female,Elderly (65+)

In [24]:
patients.to_csv('D:\\Hospital_Performance_Dashboard\\patients.csv', index=False)
doctors.to_csv('D:\\Hospital_Performance_Dashboard\\doctors.csv', index=False)
visits.to_csv('D:\\Hospital_Performance_Dashboard\\visits.csv', index=False)

print("Saved: patients.csv  ", patients.shape)
print("Saved: doctors.csv   ", doctors.shape)
print("Saved: visits.csv    ", visits.shape)

Saved: patients.csv   (18655, 4)
Saved: doctors.csv    (500, 6)
Saved: visits.csv     (18655, 17)

# 7. Connect to Database

In [25]:
engine = create_engine("postgresql+psycopg2://postgres:125890@localhost:5432/Hospital_db")

df.to_sql('hospital',engine,if_exists='replace',index=False)
patients.to_sql('patients',engine,if_exists='replace',index=False)
doctors.to_sql('doctors',engine,if_exists='replace',index=False)
visits.to_sql('visits',engine,if_exists='replace',index=False)

print("Connection Successful")

Connection Successful

In [26]:
pd.read_sql("SELECT COUNT(*) FROM hospital",engine)

   count
0  18655

In [27]:
def run_sql(query):
    """Run a SQL query"""
    return pd.read_sql_query(query,engine)